[package]
name = "mbtree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.137"
priority-queue = "1.3.0"

[dev-dependencies]
mockall = "0.11.2"
rand = "0.8.5"
